### ISSUE TITLE
Remove peerDependencies line

### ISSUE THREAD

**Issue by jsumners** [btmorex/hapi-server-session#1]
The `peerDependencies` option is going bye-bye and it's now preventing the module from being installed when Hapi 12.x is already installed.

**Comment by sharang1** [comment]
same issue is for all >11 versions.

**Comment by khalidHussain** [comment]
any plan on making this change to make it work with newer versions? @btmorex

**Comment by jsumners** [comment]
@khalidHussain in the interim, you might check out `hapi-easy-session`.

**Comment by khalidHussain** [comment]
@jsumners thanks man, you made my day

**Comment by btmorex** [comment]
`peerDependencies` can't be removed because hapi can have breaking changes that affect the plugin. For example, hapi version 15 defaults the `SameSite` cookie flag to `Strict`, which prevents sessions from working on cross site requests. That said [v2.0.5](https://github.com/btmorex/hapi-server-session/releases/tag/v2.0.5) supports hapi through version 14 and [v3.0.0](https://github.com/btmorex/hapi-server-session/releases/tag/v3.0.0) supports hapi version 15

**Comment by jsumners** [comment]
I have to disagree. It's really up to the user of the module to manage their cookies. A simple note in the readme about cookie requirements should suffice.

**Comment by btmorex** [comment]
I guess we'll just have to agree to disagree. I think plugins, etc. should be secure by default without requiring a user to read the docs carefully. For example, hapi-server-session has always set the HttpOnly and Secure flags because essentially they should always be set for session cookies. Why require users of the plugin to know that? For what it's worth, the hapi project seems to agree because version 15 sets them by default.
